version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 -
      - $HOME/.local/bin/poetry config virtualenvs.create false
    pre_install:
      - $HOME/.local/bin/poetry export --only=docs -o requirements.txt

python:
  install:
    - requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml
