name: Check Commit

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Check Lints
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup poetry
        run: pipx install poetry==1.8.3

      - name: Generate datefile
        run: echo "lint-$(date +%U)" > datefile

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: |
            pyproject.toml
            datefile

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --sync --only=main,type,dev

      - name: Run lints
        run: make lint

  test:
    name: Check Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup poetry
        run: pipx install poetry==1.8.3

      - name: Generate datefile
        run: echo "test-$(date +%U)" > datefile

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: |
            pyproject.toml
            datefile

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --sync --only=main,dev

      - name: Run tests
        run: make test

  docs:
    name: Check Docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup poetry
        run: pipx install poetry==1.8.3

      - name: Generate datefile
        run: echo "docs-$(date +%U)" > datefile

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: poetry
          cache-dependency-path: |
            pyproject.toml
            datefile

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --sync --only=docs

      - name: Check build
        run: make docs-build
