name: Check Commit

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup poetry
        run: pipx install poetry

      - name: Generate datefile
        run: echo "lint-$(date +%U)" > datefile

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: |
            pyproject.toml
            datefile

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --only=main,type,dev

      - name: Run lints
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup poetry
        run: pipx install poetry

      - name: Generate datefile
        run: echo "test-$(date +%U)" > datefile

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: |
            pyproject.toml
            datefile

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --only=main,dev

      - name: Run tests
        run: make test

  docs:
    name: Docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup poetry
        run: pipx install poetry

      - name: Generate datefile
        run: echo "docs-$(date +%U)" > datefile

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: poetry
          cache-dependency-path: |
            pyproject.toml
            datefile

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --only=docs

      - name: Check build
        run: make docs-build
