name: Docs

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup poetry
        run: pipx install poetry

      - name: Generate datefile
        run: echo "docs-$(date +%U)" > datefile

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: poetry
          cache-dependency-path: |
            pyproject.toml
            datefile

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --only=docs

      - name: Check build
        run: make docs-build
